FROM pytorch/pytorch:latest

WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY requirements.txt /workspace/

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install bitsandbytes --upgrade && \
    pip install vllm>=0.4.3 && \
    pip install --no-cache-dir -r /workspace/requirements.txt && \
    pip uninstall transformer-engine -y
